stages:
  - test
  - docker_build
test:
  image: "python:3"
  stage: test
  script:
    - make deps
    - make test
    #- pip install -r requirements.txt
    #- pip install -r test_requirements.txt
    #- PYTHONPATH=. py.test --verbose -s
docker:
  image: docker:stable
  services:
    - docker:dind
  stage: docker_build
  script:
    - apk add --update make
    - make docker_build
    #- docker build -t myapp .
